name: mix
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        backend: [mnesia, rocksdb]
    env:
      KVS_BACKEND: ${{ matrix.backend }}
    steps:
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y liblz4-dev libsnappy-dev zlib1g-dev libbz2-dev libzstd-dev build-essential libcsv3 libcsv-dev cmake
    - uses: erlef/setup-beam@v1
      with:
        otp-version: 27.x
        elixir-version: 1.18.x
    - name: Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix deps.clean --unused
    - name: Compilation
      run: mix compile
    - name: Test
      run: mix test

